"""created foreign key in receipts model that refers to product purchased

Revision ID: 4fe1f3d68e4b
Revises: 41b9381b9670
Create Date: 2023-07-18 16:56:14.076962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fe1f3d68e4b'
down_revision = '41b9381b9670'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_receipts_product_id_decks'), 'decks', ['product_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_receipts_product_id_decks'), type_='foreignkey')
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###
