"""changed receipt model

Revision ID: 5de9759aac67
Revises: 8b595b3fffaa
Create Date: 2023-07-20 20:51:10.117285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5de9759aac67'
down_revision = '8b595b3fffaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_receipts_product_id_decks', type_='foreignkey')
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_receipts_product_id_decks', 'decks', ['product_id'], ['id'])

    # ### end Alembic commands ###
