"""added name to spots

Revision ID: 66132181a45e
Revises: cb4835e3e5c1
Create Date: 2023-07-11 18:29:38.312731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66132181a45e'
down_revision = 'cb4835e3e5c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spots', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
