"""minor changes to deck and receipt tables

Revision ID: a7fbeda9f35a
Revises: 4fe1f3d68e4b
Create Date: 2023-07-19 20:09:52.934988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7fbeda9f35a'
down_revision = '4fe1f3d68e4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_product_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('stripe_price_id', sa.String(), nullable=True))

    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.drop_column('address')
        batch_op.drop_column('paid_in_full')
        batch_op.drop_column('first_name')
        batch_op.drop_column('last_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('paid_in_full', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('address', sa.VARCHAR(), nullable=False))

    with op.batch_alter_table('decks', schema=None) as batch_op:
        batch_op.drop_column('stripe_price_id')
        batch_op.drop_column('stripe_product_id')

    # ### end Alembic commands ###
