"""deck_name must now be unique

Revision ID: ad61ed2eaac8
Revises: a7fbeda9f35a
Create Date: 2023-07-20 14:55:34.793183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad61ed2eaac8'
down_revision = 'a7fbeda9f35a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decks', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['deck_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
