"""rebuilt tables

Revision ID: b96a07979c12
Revises: 66132181a45e
Create Date: 2023-07-17 18:48:55.385659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b96a07979c12'
down_revision = '66132181a45e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_spots')
    op.drop_table('user_decks')
    with op.batch_alter_table('decks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_decks_user_id_users'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('spots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_spots_user_id_users'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spots', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_spots_user_id_users'), type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('decks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_decks_user_id_users'), type_='foreignkey')
        batch_op.drop_column('user_id')

    op.create_table('user_decks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('deck_id', sa.INTEGER(), nullable=True),
    sa.Column('wishlist', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], name='fk_user_decks_deck_id_decks'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_user_decks_user_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_spots',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('spots', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['spots'], ['spots.id'], name='fk_user_spots_spots_spots'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_user_spots_user_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
