"""changed tables

Revision ID: cb4835e3e5c1
Revises: 24afa9c44acb
Create Date: 2023-07-10 16:56:28.798941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb4835e3e5c1'
down_revision = '24afa9c44acb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_spots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spots', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_user_spots_spots_spots'), 'spots', ['spots'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_spots', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_spots_spots_spots'), type_='foreignkey')
        batch_op.drop_column('spots')

    # ### end Alembic commands ###
